//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WPFMetroManagement.NetFramework.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Line
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Line()
        {
            this.Tickets = new HashSet<Ticket>();
        }
    
        public int id { get; set; }
        public int idCompany { get; set; }
        public string lineName { get; set; }
        public string lineType { get; set; }
        public int lineStartId { get; set; }
        public int lineEndId { get; set; }
        public string stops { get; set; }
        public string openTime { get; set; }
        public string closeTime { get; set; }
        public string awTime { get; set; }
        public string statusLine { get; set; }
    
        public virtual Company Company { get; set; }
        public virtual Station Station { get; set; }
        public virtual Station Station1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Ticket> Tickets { get; set; }
    }
}
