//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WPFMetroManagement.NetFramework.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ticket
    {
        public int id { get; set; }
        public string tType { get; set; }
        public int idRoute { get; set; }
        public Nullable<System.DateTime> registerDate { get; set; }
        public Nullable<System.DateTime> expiryDate { get; set; }
        public Nullable<int> price { get; set; }
        public Nullable<bool> isUsed { get; set; }
        public Nullable<bool> isSell { get; set; }
    
        public virtual Line Line { get; set; }
    }
}
