//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WPFMetroManagement.NetFramework.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class User
    {
        public int id { get; set; }
        public string userName { get; set; }
        public string userPass { get; set; }
        public Nullable<int> idCompany { get; set; }
    
        public virtual Company Company { get; set; }
    }
}
